spring.application.name=rocket

spring.datasource.url=jdbc:mysql://localhost:3306/eventManagement
spring.datasource.username=root
spring.datasource.password=yuva@1602

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
